- name: Include vault vars
  include_vars: defaults/vault.yml
  failed_when: no

- name: Ensure valid action
  assert:
    that:
    - action is defined
    - action in role_actions
    - proxmox_host is defined
    - proxmox_user is defined
    - proxmox_pass is defined
  tags:
  - always

- name: Authenticate to Proxmox API
  block:
  - uri:
      validate_certs: no
      url: "https://{{ proxmox_host }}/api2/json/access/ticket"
      method: POST
      body_format: form-urlencoded
      body:
        username: "{{ proxmox_user }}"
        password: "{{ proxmox_pass }}"
    register: proxmox_auth
  - set_fact:
      proxmox_auth_headers:
        Cookie: "PVEAuthCookie={{ proxmox_auth.json.data.ticket }}"
        CSRFPreventionToken: "{{ proxmox_auth.json.data.CSRFPreventionToken }}"
  tags:
  - always

- name: "Call {{action}} action"
  include_tasks:
    file: "{{action}}.yml"
  tags:
  - always
